//This file was generated by script swreg2regmap.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_Ax 2
#define KNN_Bx 3
#define KNN_Ay 4
#define KNN_By 5
#define KNN_LABEL 6
#define KNN_acesso 7
#define KNN_Dist 8
#define KNN_Out 9
#define KNN_Out2 10
#define KNN_PIP 11
